# Site settings
title: PM 周刊
email: mail@pmweekly.com
description: PM 周刊 -- 每周周一晚上 9 点推送经人工筛选出的产品精品文章 powered by pmweekly.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pmweekly.com"

# Build settings
markdown: kramdown

permalink: /issues/:title

exclude: ["./book"]
